In [2]:
import numpy as np

def sigmoid(x):
    return 1.0/(1.0 + np.exp(-x))

X = np.array([ [0,1],[1,1],[1,0] ])
y = np.array([[0,1,0]]).T

print X
print y

syn0 = 2*np.random.random((2,3)) - 1
syn1 = 2*np.random.random((3,1)) - 1

print syn0
print syn1

for j in xrange(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))    
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)
    
print l2

print l2 > 0.5

T = np.array([[0,0]])
l1 = 1/(1+np.exp(-(np.dot(T,syn0))))
l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
print
print l2 > 0.5

T = np.array([[1,0]])
l1 = 1/(1+np.exp(-(np.dot(T,syn0))))
l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
print
print l2 > 0.5

T = np.array([[1,1]])
l1 = 1/(1+np.exp(-(np.dot(T,syn0))))
l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
print
print l2 > 0.5

[[0 1]
 [1 1]
 [1 0]]
[[0]
 [1]
 [0]]
[[-0.33930236  0.34318573 -0.16939002]
 [ 0.79990303  0.4323406  -0.97973538]]
[[ 0.74309326]
 [-0.16382076]
 [ 0.61389979]]
[[ 0.0041921 ]
 [ 0.9946251 ]
 [ 0.00290009]]
[[False]
 [ True]
 [False]]

[[False]]

[[False]]

[[ True]]
